# Generated by Django 3.0.5 on 2020-04-06 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pontoturistico_atracoes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pontoturistico',
            options={'verbose_name_plural': 'Pontos turísticos'},
        ),
    ]
