# Generated by Django 3.0.5 on 2020-04-06 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atracao',
            options={'verbose_name_plural': 'Atrações'},
        ),
    ]
